icons_format = "{icon}"

[icons]
icons = "material-nf"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#0f0f0f"
idle_fg = "#ebdbb2"
info_bg = "#458588"
info_fg = "#ebdbb2"
good_bg = "#98971a"
good_fg = "#ebdbb2"
warning_bg = "#d79921"
warning_fg = "#ebdbb2"
critical_bg = "#cc241d"
critical_fg = "#ebdbb2"
separator = ""
separator_bg = "#0f0f0f"
separator_fg = "#0f0f0f"

# [[block]]
# block = "pomodoro"
# format = " $icon{ $message|} "
# notify_cmd = "dunstify '{msg}'"

# [[block]]
# block = "notify"
# format = " $icon {$paused{Off}|On} {($notification_count.eng(w:1))|}"
# driver = "dunst"

[[block]]
block = "scratchpad"
format = "  $count "

# [[block]]
# block = "temperature"
# format = " $icon $average "
# format_alt = " $icon $min/$average/$max "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "  $utilization "
format_alt = "  $frequency $barchart "
interval = 2

[[block]]
block = "custom"
format = "   $text "
command = "free -h | awk '/Mem:/ {print $3}'"
shell = "bash"
interval = 2

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used/$total "
format_alt = " $icon $free/$percentage "

[[block]]
block = "net"
format = " ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) "
format_alt = " $icon $ip "
device = "eno1"

[[block]]
block = "sound"
format = " $icon $volume "
format_alt = " $icon $active_port "
max_vol = 100
show_volume_when_muted = true
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "  $timestamp.datetime(f:'%a %b %d') 󰥔 $timestamp.datetime(f:'%I:%M %p') "
